apiVersion: v1
kind: PersistentVolume
metadata:
  name: servicex-cache
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/host_mnt/c/cache"
